// ─── FLUX (Black Forest Labs) Provider ─────────────────────────────────────────

import { BaseStagingProvider } from "./base";
import type {
  StagingRequest,
  StagingResult,
  ProviderCapabilities,
  GeneratedImage,
} from "../types";
import { buildStagingPrompt, wrapPromptForProvider } from "../prompts";
import fs from "fs";

export class FluxProvider extends BaseStagingProvider {
  readonly name = "flux" as const;
  readonly capabilities: ProviderCapabilities = {
    canGenerate: true,
    canEdit: true,
    canAnalyze: false,
    canUpscale: false,
    canRecolor: true,
    maxImages: 4,
    maxResolution: { width: 2048, height: 2048 },
    costPerImage: { low: 0.014, medium: 0.03, high: 0.07 },
  };

  private readonly BFL_API_BASE = "https://api.bfl.ml/v1";

  private getApiKey(): string {
    return process.env.FLUX_API_KEY || "";
  }

  isAvailable(): boolean {
    return !!this.getApiKey();
  }

  async generateDesign(request: StagingRequest): Promise<StagingResult> {
    const startTime = Date.now();
    const apiKey = this.getApiKey();

    if (!apiKey) {
      return this.errorResult("FLUX API key not configured");
    }

    try {
      const modeMap: Record<string, string> = {
        stage_empty: "stage",
        redesign: "redesign",
        wall_recolor: "recolor_wall",
        cabinet_recolor: "recolor_cabinet",
        remodel_kitchen: "remodel",
        remodel_bathroom: "remodel",
        remove_objects: "remove",
      };

      const basePrompt = buildStagingPrompt({
        roomType: request.roomType,
        designStyle: request.designStyle,
        customPrompt: request.prompt,
        promptPrefix: request.promptPrefix,
        promptSuffix: request.promptSuffix,
        targetColor: request.targetColor,
        mode: (modeMap[request.mode] || "stage") as "stage" | "redesign" | "recolor_wall" | "recolor_cabinet" | "remodel" | "remove",
      });

      const prompt = wrapPromptForProvider(basePrompt, "flux");
      const numImages = Math.min(request.numImages || 1, 4);

      // Determine model based on quality
      const quality = request.quality || "medium";
      const modelMap = {
        low: "flux.2-klein",
        medium: "flux.2-pro",
        high: "flux.2-max",
      };
      const model = modelMap[quality];

      // Determine resolution
      const width = request.resolution?.width || 1024;
      const height = request.resolution?.height || 1024;

      // Check if we have an input image for img2img
      const hasInputImage = request.inputImagePath && fs.existsSync(request.inputImagePath);

      const images: GeneratedImage[] = [];

      for (let i = 0; i < numImages; i++) {
        try {
          let requestBody: Record<string, unknown>;

          if (hasInputImage) {
            // Use the img2img / fill endpoint
            const imageBuffer = fs.readFileSync(request.inputImagePath);
            const base64 = imageBuffer.toString("base64");

            requestBody = {
              prompt: prompt,
              image: base64,
              width,
              height,
              steps: quality === "high" ? 50 : quality === "medium" ? 28 : 15,
              guidance: request.guidanceScale || 7.5,
              seed: request.seed,
            };
          } else {
            // Text-to-image generation
            requestBody = {
              prompt: prompt,
              width,
              height,
              steps: quality === "high" ? 50 : quality === "medium" ? 28 : 15,
              guidance: request.guidanceScale || 7.5,
              seed: request.seed,
            };
          }

          // Submit the generation request
          const submitResponse = await fetch(`${this.BFL_API_BASE}/${model}`, {
            method: "POST",
            headers: {
              "X-Key": apiKey,
              "Content-Type": "application/json",
            },
            body: JSON.stringify(requestBody),
          });

          if (!submitResponse.ok) {
            const err = await submitResponse.text();
            console.error(`FLUX submit error: ${err}`);
            continue;
          }

          const submitData = await submitResponse.json();
          const taskId = submitData.id;

          if (!taskId) continue;

          // Poll for results
          const image = await this.pollForResult(apiKey, taskId, prompt);
          if (image) {
            images.push(image);
          }
        } catch (error) {
          console.error(`FLUX generation ${i} failed:`, error);
        }
      }

      if (images.length === 0) {
        return this.errorResult("No images generated by FLUX", Date.now() - startTime);
      }

      const costPerImage = this.capabilities.costPerImage[quality];
      const totalCost = costPerImage * images.length;

      return this.successResult(images, totalCost, Date.now() - startTime, {
        model,
        quality,
        promptUsed: prompt,
      });
    } catch (error) {
      return this.errorResult(
        `FLUX error: ${error instanceof Error ? error.message : String(error)}`,
        Date.now() - startTime
      );
    }
  }

  private async pollForResult(
    apiKey: string,
    taskId: string,
    promptUsed: string,
    maxAttempts: number = 60,
    intervalMs: number = 2000
  ): Promise<GeneratedImage | null> {
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      await new Promise((resolve) => setTimeout(resolve, intervalMs));

      try {
        const response = await fetch(`${this.BFL_API_BASE}/get_result?id=${taskId}`, {
          headers: { "X-Key": apiKey },
        });

        if (!response.ok) continue;

        const data = await response.json();

        if (data.status === "Ready" && data.result?.sample) {
          return {
            url: data.result.sample,
            width: data.result.width || 1024,
            height: data.result.height || 1024,
            format: "jpeg",
            promptUsed,
            seed: data.result.seed,
          };
        }

        if (data.status === "Error") {
          console.error("FLUX task failed:", data.result);
          return null;
        }

        // Still processing — continue polling
      } catch {
        // Network error — retry
      }
    }

    console.error(`FLUX task ${taskId} timed out`);
    return null;
  }
}
